version: "3.7"
services:
  customer_service:
    image: .
    restart: always
    depends_on:
      - mongodb_customer
    ports:
      - 9090:8080
    command:
      - apt update;
      - apt install git maven -y;
      - git clone https://github.com/lmfacchini/customer.git;
      - mvn clean install spring-boot:run
  mongodb_customer:
    image: mongo
    ports:
      - 27018:27017