version: "3.7"
services:
  customer_service:
    image: mongo
    restart: always
    ports:
      - 8080:8181
    command:
      - bash -c
      - apt-get update;
      - apt-get install git maven -y;
      - git clone https://github.com/lmfacchini/customer.git;
      - mvn clean install spring-boot:run